### PR TITLE
[WO-905] Implemented COMPRESS=DEFLATE support using pako

### PR DESCRIPTION
**Pull request by andris9**
Support compression as defined in [RFC4978](https://tools.ietf.org/html/rfc4978). Deflate implementation is from http://nodeca.github.io/pako/. 

Unfortunately pako didn't have deflateRaw streaming support out of the box, so I pathced the pako distribution file with https://github.com/creationix/tedit-node-backend/blob/master/zlib-codec.js and included pako.js in the source. Hopefully this gets fixed in the future (see https://github.com/nodeca/pako/issues/37) so we could drop pako.js and include it as a dependency in package.json.

Compression support is not turned on by default. To use compression, set `enableCompression` option for BrowserBox to `true`. See also the example file *examples/compression-example.js* for usage example (this example runs in Node).

### CODE REVIEW

**Comment by andris9** [comment]
The changes we did can be found here: https://github.com/whiteout-io/browserbox/blob/master/src/browserbox-pako.js#L792-L842 and 
https://github.com/whiteout-io/browserbox/blob/master/src/browserbox-pako.js#L381-L432 but these are limited to our specific use case, have hardcoded constants etc. so the updates are probably not suitable for an actual patch.

**Comment by puzrin** [comment]
I think patch needed for this deflate wrapper line https://github.com/nodeca/pako/blob/master/lib/deflate.js#L227

```js
    if (strm.avail_out === 0 || (strm.avail_in === 0 && (_mode === Z_FINISH || mode === Z_SYNC_FLUSH || mode === Z_PARTIAL_FLUSH))) {
```

...and the same for inflate wrapper.

But that needs checks, tests ans so on. If you have some time for it, it would be nice.

**Comment by puzrin** [comment]
updated example to more compact & universal

**Comment by puzrin** [comment]
@andris9 , last pako release has correct Z_SYNC_FLUSH support.

**Comment by andris9** [comment]
Great! Once I have the time I test it out, can't wait to drop our current fork.

**Pull request merged**
